site_name: Symbiose Business Foundations
site_url: https://doc.symbiose.run/
docs_dir: docs
# dev_addr: 127.0.0.1:8000
repo_name: symbiose
repo_url: https://github.com/yesbabylon/symbiose
edit_uri: ""
theme:
  name: material
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/sb_logo.png'
  palette:
    scheme: default
    primary: blue grey
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - 'assets/css/extra.css'
plugins:
  - search
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers:
extra:
  version:
    provider: mike
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Welcome':
      - 'Symbiose': 'index.md'
      - 'Release notes': 'welcome/release-notes.md'
      - 'Contribution Guide': 'welcome/contribution-guide.md'
  - 'Getting Started': 'developer-manual/install-symbiose.md'
  - 'User ':
      - 'Account': 'user-manual/user-account.md'
      - 'Timetrack':
          - 'Summary': 'user-manual/timetrack/index.md'
          - 'Time entry': 'user-manual/timetrack/time-entry.md'
          - 'Project': 'user-manual/timetrack/project.md'
          - 'Sale Model': 'user-manual/timetrack/time-entry-sale-model.md'
  - 'Developer':
      - 'Packages': 'developer-manual/package-description.md'
      - 'Finance':
          - 'Summary': 'developer-manual/finance/index.md'
          - 'Classes': 'developer-manual/finance/classes.md'
          - 'Uml': 'developer-manual/finance/uml.md'
      - 'Sale':
          - 'Summary': 'developer-manual/sale/index.md'
          - 'Classes':
              - 'Catalog': 'developer-manual/sale/classes/catalog.md'
              - 'Price': 'developer-manual/sale/classes/price.md'
              - 'Customer': 'developer-manual/sale/classes/customer.md'
              - 'Sale Entry': 'developer-manual/sale/classes/sale-entry.md'
              - 'Receivable': 'developer-manual/sale/classes/receivable.md'
              - 'Invoice': 'developer-manual/sale/classes/invoice.md'
              - 'Subscription': 'developer-manual/sale/classes/subscription.md'
              - 'Pay': 'developer-manual/sale/classes/pay.md'
          - 'Actions':
              - 'Sale Entry': 'developer-manual/sale/actions/sale-entry.md'
              - 'Receivable': 'developer-manual/sale/actions/receivable.md'
              - 'Receivable Queue': 'developer-manual/sale/actions/receivable-queue.md'
              - 'Invoice': 'developer-manual/sale/actions/invoice.md'
              - 'Subscription': 'developer-manual/sale/actions/subscription.md'
          - 'Uml': 'developer-manual/sale/uml.md'
      - 'Inventory':
          - 'Summary': 'developer-manual/inventory/index.md'
          - 'Classes':
              - 'Inventory': 'developer-manual/inventory/classes.md'
              - 'Service': 'developer-manual/inventory/classes-service.md'
              - 'Server': 'developer-manual/inventory/classes-server.md'
          - 'Actions':
            - 'Bulk Expiration': 'developer-manual/inventory/actions-bulkExpiration.md'
            - 'Check Expiration': 'developer-manual/inventory/actions-checkExpiration.md'
          - 'Uml': 'developer-manual/inventory/uml.md'
      - 'Timetrack':
          - 'Summary': 'developer-manual/timetrack/index.md'
          - 'Classes': 'developer-manual/timetrack/classes.md'
          - 'Actions': 'developer-manual/timetrack/actions-checkExpiration.md'
          - 'Uml': 'developer-manual/timetrack/uml.md'
